

CREATE TABLE product(      
id INT PRIMARY KEY,      
name VARCHAR(30) NOT NULL );

INSERT INTO product VALUES (2020,"PUMA SHOES");
INSERT INTO product VALUES (2010,"SPORT SHOES");
INSERT INTO product VALUES (2030,"LANCER SHOES");
INSERT INTO product VALUES (2040,"BUCKAROO SHOES");
INSERT INTO product VALUES (2050,"FORMAL SHOES");

select * from product
